### ISSUE TITLE
Amount and paid amount in cron

### ISSUE THREAD

**Issue by ariferol01** [bgokcol/bsc-pay#7]
What if paid_amount less then amount in payments table?
I tried:
`[Payment #1 | 0xdeaeb986927d6543578317259df7f2e315a69251 | Balance: 0.0012900000 | Payment Amount: 0.0012900000]` 
amount = 0.0013950000
paid_amount = 0.0012900000
Not sending amount to wallet

**Comment by bgokcol** [comment]
Hi, it doesn't verify the transaction until wallet balance reaches "amount" value. It keeps in "payment_waiting" status.

**Comment by ariferol01** [comment]
> Hi, it doesn't verify the transaction until wallet balance reaches "amount" value. It keeps in "payment_waiting" status.

Thanks, I want to accept payments that meet the `if(paid_amount > 0)` condition. 
How can i make like this? 
If "paid_amount" is less than "amount", if i update the "amount" column in the "payments" table, does it work?
Because I want to use this library on a site where everyone can add any amount of balance they want.

**Comment by bgokcol** [comment]
I think that you can create a payment with using 0.00001 as "payment_amount" value. So it'll accept anything over 0.00001 and you'll find the paid_amount in database.
