### ISSUE TITLE
When?

### ISSUE THREAD

**Issue by poejanetwork** [bgokcol/bsc-pay#8]
What's Next?
I will add user and admin dashboard.
I will add support for stable coins like BUSD, USDT, DAI.
Transfer fee (gas limit & gas price) is provided by the user for now. I will make it automatic in the future.

**Comment by bgokcol** [comment]
This project is pretty bad coded, I don't think it worths working on it. Still could be useful to understand basics of payment process.

**Comment by poejanetwork** [comment]
This project is pretty bad coded, I don't think it worths working on it. Still could be useful to understand basics of payment process.

So which is the good one for payment process? Please share
